# Generated by Django 5.2.6 on 2025-10-29 19:28

import django.db.models.deletion
import django.utils.timezone
import reels.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=reels.models.reel_video_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=reels.models.reel_video_path)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, max_length=2200)),
                ('audio_name', models.CharField(blank=True, max_length=200)),
                ('audio_url', models.URLField(blank=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReelComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=500)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reels.reelcomment')),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reels.reel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reel_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReelCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reels.reelcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reel_comment_likes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReelLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reels.reel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reel_likes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReelTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='reels.reel')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_reels', to='posts.tag')),
            ],
            options={
                'db_table': 'reel_tags',
            },
        ),
        migrations.CreateModel(
            name='ReelView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('watch_time', models.FloatField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='reels.reel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reel_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reel_views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='reels.reel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_reels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['user', '-created_at'], name='reels_user_id_47eb8a_idx'),
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['-created_at'], name='reels_created_8f0561_idx'),
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['-views_count'], name='reels_views_c_1f85e8_idx'),
        ),
        migrations.AddIndex(
            model_name='reelcomment',
            index=models.Index(fields=['reel', '-created_at'], name='reel_commen_reel_id_afffcf_idx'),
        ),
        migrations.AddIndex(
            model_name='reelcomment',
            index=models.Index(fields=['parent', '-created_at'], name='reel_commen_parent__4d8e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='reelcomment',
            index=models.Index(fields=['user', '-created_at'], name='reel_commen_user_id_10ec6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reelcommentlike',
            unique_together={('comment', 'user')},
        ),
        migrations.AddIndex(
            model_name='reellike',
            index=models.Index(fields=['reel', '-created_at'], name='reel_likes_reel_id_aac978_idx'),
        ),
        migrations.AddIndex(
            model_name='reellike',
            index=models.Index(fields=['user', '-created_at'], name='reel_likes_user_id_54251f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reellike',
            unique_together={('reel', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='reeltag',
            unique_together={('reel', 'tag')},
        ),
        migrations.AddIndex(
            model_name='reelview',
            index=models.Index(fields=['reel', '-viewed_at'], name='reel_views_reel_id_df0bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='reelview',
            index=models.Index(fields=['user', '-viewed_at'], name='reel_views_user_id_a2604a_idx'),
        ),
        migrations.AddIndex(
            model_name='savedreel',
            index=models.Index(fields=['user', '-created_at'], name='saved_reels_user_id_9e12a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedreel',
            unique_together={('user', 'reel')},
        ),
    ]
