# Generated by Django 5.2.6 on 2025-10-29 19:28

import django.db.models.deletion
import django.utils.timezone
import stories.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('media', models.FileField(upload_to=stories.models.story_media_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=stories.models.story_media_path)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, max_length=500)),
                ('viewers_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'db_table': 'stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='highlights/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'story_highlights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HighlightStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_highlights', to='stories.story')),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='stories.storyhighlight')),
            ],
            options={
                'db_table': 'highlight_stories',
                'ordering': ['order', '-added_at'],
            },
        ),
        migrations.CreateModel(
            name='HighlightPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_highlights', to='posts.post')),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='stories.storyhighlight')),
            ],
            options={
                'db_table': 'highlight_posts',
                'ordering': ['order', '-added_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='stories.story')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'story_views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['user', '-created_at'], name='stories_user_id_b336dc_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['expires_at'], name='stories_expires_a4b2b7_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['-created_at'], name='stories_created_caa2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='storyhighlight',
            index=models.Index(fields=['user', '-created_at'], name='story_highl_user_id_bc8ca3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='highlightstory',
            unique_together={('highlight', 'story')},
        ),
        migrations.AlterUniqueTogether(
            name='highlightpost',
            unique_together={('highlight', 'post')},
        ),
        migrations.AddIndex(
            model_name='storyview',
            index=models.Index(fields=['story', '-viewed_at'], name='story_views_story_i_ced952_idx'),
        ),
        migrations.AddIndex(
            model_name='storyview',
            index=models.Index(fields=['viewer', '-viewed_at'], name='story_views_viewer__a5c03d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storyview',
            unique_together={('story', 'viewer')},
        ),
    ]
