# Generated by Django 5.2.6 on 2025-10-29 19:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.BooleanField(default=False, help_text='Private account')),
                ('show_activity_status', models.BooleanField(default=True, help_text="Show when you're active")),
                ('allow_story_sharing', models.BooleanField(default=True, help_text='Allow others to share your story')),
                ('allow_story_replies', models.BooleanField(default=True, help_text='Allow replies to your story')),
                ('allow_comments', models.BooleanField(default=True, help_text='Allow comments on your posts')),
                ('allow_comment_likes', models.BooleanField(default=True, help_text='Allow likes on comments')),
                ('hide_like_counts', models.BooleanField(default=False, help_text='Hide like counts on your posts')),
                ('allow_tags', models.BooleanField(default=True, help_text='Allow others to tag you')),
                ('manual_tag_approval', models.BooleanField(default=False, help_text='Manually approve tags')),
                ('allow_mentions', models.BooleanField(default=True, help_text='Allow others to mention you')),
                ('mentions_from', models.CharField(choices=[('everyone', 'Everyone'), ('following', 'People you follow'), ('no_one', 'No one')], default='everyone', max_length=20)),
                ('allow_messages_from', models.CharField(choices=[('everyone', 'Everyone'), ('following', 'People you follow'), ('no_one', 'No one')], default='everyone', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hide_story_from', models.ManyToManyField(blank=True, help_text="Users who can't see your stories", related_name='hidden_stories_from', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Privacy Settings',
                'db_table': 'privacy_settings',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('email_change', 'Email Change'), ('profile_update', 'Profile Update'), ('settings_change', 'Settings Change')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_b8c999_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blocked_users',
                'ordering': ['-blocked_at'],
                'indexes': [models.Index(fields=['blocker', '-blocked_at'], name='blocked_use_blocker_55f84c_idx'), models.Index(fields=['blocked'], name='blocked_use_blocked_850a24_idx')],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
        migrations.CreateModel(
            name='CloseFriendsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('close_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_friend_of', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_friends_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'close_friends',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'close_friend')},
            },
        ),
        migrations.CreateModel(
            name='MutedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mute_posts', models.BooleanField(default=True)),
                ('mute_stories', models.BooleanField(default=True)),
                ('mute_reels', models.BooleanField(default=True)),
                ('muted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('muted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_by', to=settings.AUTH_USER_MODEL)),
                ('muter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'muted_users',
                'ordering': ['-muted_at'],
                'unique_together': {('muter', 'muted')},
            },
        ),
        migrations.CreateModel(
            name='RestrictedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restricted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('restricted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_by', to=settings.AUTH_USER_MODEL)),
                ('restrictor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'restricted_users',
                'ordering': ['-restricted_at'],
                'unique_together': {('restrictor', 'restricted')},
            },
        ),
    ]
