# Generated by Django 5.2.6 on 2025-10-29 19:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_like', models.BooleanField(default=False)),
                ('email_on_comment', models.BooleanField(default=True)),
                ('email_on_follow', models.BooleanField(default=True)),
                ('email_on_mention', models.BooleanField(default=True)),
                ('push_on_like', models.BooleanField(default=True)),
                ('push_on_comment', models.BooleanField(default=True)),
                ('push_on_follow', models.BooleanField(default=True)),
                ('push_on_mention', models.BooleanField(default=True)),
                ('push_on_story_view', models.BooleanField(default=False)),
                ('notify_on_like', models.BooleanField(default=True)),
                ('notify_on_comment', models.BooleanField(default=True)),
                ('notify_on_follow', models.BooleanField(default=True)),
                ('notify_on_mention', models.BooleanField(default=True)),
                ('notify_on_story_view', models.BooleanField(default=True)),
                ('pause_all', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like_post', 'Post Like'), ('like_comment', 'Comment Like'), ('comment', 'Comment on Post'), ('reply', 'Comment Reply'), ('follow', 'New Follower'), ('mention', 'Mention'), ('story_view', 'Story View'), ('post_tag', 'Tagged in Post')], max_length=20)),
                ('target_type', models.CharField(blank=True, max_length=20)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_2d3764_idx'), models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_dde14f_idx'), models.Index(fields=['sender', '-created_at'], name='notificatio_sender__6aaec3_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=20)),
                ('target_type', models.CharField(max_length=20)),
                ('target_id', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('is_read', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_groups', to=settings.AUTH_USER_MODEL)),
                ('senders', models.ManyToManyField(related_name='grouped_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_groups',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['recipient', '-last_updated'], name='notificatio_recipie_4a3f36_idx')],
                'unique_together': {('recipient', 'notification_type', 'target_type', 'target_id')},
            },
        ),
    ]
