# Generated by Django 6.0.1 on 2026-01-29 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='email_on_comment',
            new_name='call_sound_enabled',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='email_on_like',
            new_name='email_on_group_message',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='push_on_story_view',
            new_name='email_on_message',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='email_on_follow',
            new_name='group_message_sound_enabled',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='email_on_mention',
            new_name='high_priority_notifications',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='notify_on_comment',
            new_name='message_sound_enabled',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='notify_on_follow',
            new_name='notification_light_enabled',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='notify_on_like',
            new_name='notify_on_call',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='notify_on_story_view',
            new_name='notify_on_group_message',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='push_on_comment',
            new_name='notify_on_message',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='push_on_follow',
            new_name='notify_on_reaction',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='push_on_like',
            new_name='notify_on_reply',
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='message_tone',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='notification_light_color',
            field=models.CharField(blank=True, default='#25D366', max_length=7),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='notification_tone',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='pause_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_on_call',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_on_group_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_on_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_on_reaction',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_on_reply',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='ringtone',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='show_message_preview',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='show_sender_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='vibrate_on_call',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='vibrate_on_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('group_message', 'Group Message'), ('message_reaction', 'Message Reaction'), ('message_reply', 'Message Reply'), ('mention', 'Mention'), ('call_missed', 'Missed Call'), ('call_rejected', 'Call Rejected'), ('group_added', 'Added to Group'), ('group_removed', 'Removed from Group'), ('group_admin', 'Made Group Admin'), ('group_subject_changed', 'Group Name Changed'), ('status_view', 'Status View'), ('status_reply', 'Status Reply')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationgroup',
            name='notification_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationgroup',
            name='target_id',
            field=models.UUIDField(),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_498289_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'notification_type', 'is_read'], name='notificatio_recipie_4d450d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationgroup',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4bddd3_idx'),
        ),
    ]
